python .\lib_LTspice2Kicad.py .\lib\sym\Opamps N 2.0
python .\lib_LTspice2Kicad.py .\lib\sym\Optos Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\Comparators Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\ADC Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\DAC Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\Digital Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\FilterProducts Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\Misc Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\PowerProducts Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\References Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\SpecialFunctions Y 1.0
python .\lib_LTspice2Kicad.py .\lib\sym\Switches Y 1.0
